# Site info
site_name: PyCO2SYS
site_author: Matthew P. Humphreys
site_description: Marine carbonate system calculations in Python
site_url: https://pyco2sys.readthedocs.io/
copyright: Copyright &copy; 2020 Matthew P. Humphreys (GNU GPLv3)

# Github repo info
repo_name: mvdh7/PyCO2SYS
repo_url: https://github.com/mvdh7/PyCO2SYS

# Navigation
nav:
  - Overview: index.md
  - Calculate everything!: co2sys.md
  - References: refs.md
  - Version history: versions.md

# Appearance
theme:
  name: material
  language: en
  palette:
    primary: white
    accent: deep orange
  font:
    text: Roboto
    code: Roboto Mono

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
